version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: customer_unique_id
        tests: [not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: order_status
        tests:
          - accepted_values:
              values: ["delivered","shipped","canceled","unavailable","invoiced","processing","created","approved"]

  - name: stg_order_items
    columns:
      - name: order_id
        tests: [not_null]
      - name: order_item_id
        tests: [not_null]

  - name: stg_order_payments
    columns:
      - name: order_id
        tests: [not_null]
      - name: payment_type
        tests:
          - accepted_values:
              values: ["credit_card","boleto","voucher","debit_card","not_defined"]

  - name: stg_order_reviews
    columns:
      - name: review_id
        tests: [not_null]
      - name: review_score
        tests: [not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_sellers
    columns:
      - name: seller_id
        tests: [not_null, unique]
