version: 2

sources:
  - name: olist_raw
    database: "data-pipeline-1-498005"
    schema: olist_raw_dev
    tables:
      - name: customers
      - name: geolocation
      - name: orders
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: products
      - name: sellers
      - name: product_category_name_translation
