olist_bigquery:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:

    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
      dataset: olist_marts_dev
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      priority: interactive
      timeout_seconds: 300
      retries: 3
      threads: 4

    staging:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
      dataset: olist_marts_staging
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      priority: interactive
      timeout_seconds: 300
      retries: 3
      threads: 8

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
      dataset: olist_marts_prod
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      priority: batch
      timeout_seconds: 600
      retries: 3
      threads: 8
